name: Deploy to FTP

on:
  workflow_run:
    workflows: ["Node.js CI Production"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
          npm run export

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp://dev.blackbirduav.ca
          port: 21
          protocol: ftp
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: |
            out
            .htaccess
          server-dir: /public_html