name: Deploy to Main

on:
  workflow_run:
    workflows: ["Node.js CI Main"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: './website/package-lock.json'

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
        working-directory: ./website

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: dev.blackbirduav.ca
          port: 21
          protocol: ftp
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./website/out/
          server-dir: /